[project]
name = 'agri-trace'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.farmer-registry]
path = 'contracts/farmer-registry.clar'
clarity_version = 3
epoch = 'latest'

[contracts.payment-escrow]
path = 'contracts/payment-escrow.clar'
clarity_version = 3
epoch = 'latest'

[contracts.product-tracking]
path = 'contracts/product-tracking.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
